### ISSUE TITLE
how to set the pre and post configuration function for download of openness

### ISSUE THREAD

**Issue by davesliu** [Maroder1/Openness_examples_python#1]
Hi, Maroder1

Thanks for your idea of using pythonnet to call TIA openness.

I met a download issue of calling TIA openness API, the PLC can be downloaded to PLCSIM if I set the delegated pre ans post download callback function with no content in these two callback functiions in python script.

From the manual of TIA openness API  about download feature, it uses C# "as" operator to do some class type cast, I did not find the related operator in python. Did you meet similar issue?

Thanks in advance if you can give some comments

**Comment by Maroder1** [comment]
This one was a little bit tricky. Think I'm nearly there, but TIA keeps crashing without any error message (just closes) so it is a little hard to troubleshoot the last part. I'll get back to you as soon as I have it working!

**Comment by davesliu** [comment]
@Maroder1 
Thanks for you quick answer. Hope to get your solution :-)

BTW, I kept the pre and post download configuration callback function with no content in python script. The PLC can be downloaded to the PLCSimAdvanced, but it can't do the stopAll operation as shown in the Openness API manual.

I also use another self-write C# .dll file, which wrapped the pre & post download C# example code in TIA openness API, with this way, it can stop the running PLC before download and restart it after download. But with this way, the cons is that we don't use purely TIA Openness dll and we have to use self-wrapped C# dll file.

**Comment by Maroder1** [comment]
@davesliu 
Where I am now is that I am calling the function with translations of pre and post. But TIA just shuts down so hard to find the error. Will do some more testing this evening. Could you share the sniplet where you are able to download with no content?

**Comment by Maroder1** [comment]
@davesliu 
Small update:
Having post working

from System import Action
def PostConfigureDownload(downloadConfiguration):
        Action[dl.Configurations.StartModules](downloadConfiguration)
        if (downloadConfiguration != None):
            downloadConfiguration.CurrentSelection = dl.Configurations.StartModulesSelections.StartModule

Above will successfuly start PLCsim after download (initial state = stopped)

pre is still crashing even when adapting above, still trying to figure that one out

**Comment by Maroder1** [comment]
@davesliu 
Think I got the solution

`def PreConfigureDownload(downloadConfiguration):
   
    if (type(downloadConfiguration) is dl.Configurations.StopModules):
        if (downloadConfiguration != None):
            downloadConfiguration.CurrentSelection = dl.Configurations.StopModulesSelections.StopAll`

Will upload the code in a bit

**Comment by Maroder1** [comment]
Seems to be working. 
New file uploaded: Download.ipynb

**Comment by davesliu** [comment]
@Maroder1
Thanks a lot. That's great. I will try it :-)

**Comment by davesliu** [comment]
I previous use two below callbacks.
def pre_config_download_callback(config):
    return
def post_config_download_callback(config):
    return

.....
callback1 = Siemens.Engineering.Download.DownloadConfigurationDelegate(pre_config_download_callback)
callback2 = Siemens.Engineering.Download.DownloadConfigurationDelegate(post_config_download_callback)

Then set the callback1 and callback2 to the Download callbacks.

**Comment by davesliu** [comment]
BTW, use isinstance(downloadConfiguration, dl.Configurations.StopModules) instead of type() function may be easier.

**Comment by Maroder1** [comment]
Thanks, you're right, will change into "isinstance" this evening.
Also suspect that the if conditions aren't needed. 
Lastly your sniplet made me realize that I need to do some pythonic naming. 

Not sure yet, but perhaps it would be smart to change into IF ELIF ELSE so that the ELSE can warn in case there is a "unknown type"

**Comment by davesliu** [comment]
Thanks for your great idea. It really help me with your proposal to use python to develop Openness API related programs
