### ISSUE TITLE
Question for the out type of PLCSim C# API

### ISSUE THREAD

**Issue by davesliu** [Maroder1/Openness_examples_python#2]
Hi, Maroder1

For Below PCLSIM C# API with the out type parameter.
void GetCycleTimeMonitoringMode( out ECycleTimeMonitoringMode out_CycleTimeMonitoringMode, out Int64 out_MaxCycleTime_ns)

Do you know how to implement it with python?
I directly use the below python code:
out_CycleTimeMonitoringMode= 0
out_MaxCycleTime_ns = 0
plc_instance.GetCycleTimeMonitoringMode(out_CycleTimeMonitoringMode, out_MaxCycleTime_ns)
It seems that the two variable values are not changed and both are still 0.

BTW, did you have usage example for the Single Step and Time Span for PLCSim API, if yes, could you share some usage examples?

Thanks in advance

**Comment by Maroder1** [comment]
Hi, 
I have unfortunately not tried the PLCSIM advanced  API, nor do I have the license. 
But I like the idea of python and PLCSIM adv to create test scripts. I will defiantly look into it, just need to find time in the middle of the this "home office" situation. 

Only tip I can think of is to troubleshoot: does it work with C#, and can you modify the C# code to maybe give a hint?

Do you have some "getting started" you would like to share?

**Comment by davesliu** [comment]
@Maroder1 
Thanks for your comments.
I only begin to use PLCSIM API, I also don't have any C# code experience for this PLCSIM API.
I will try with your suggestion to wrapper the C# API with a lib, which seems not a good idea :-)
