### ISSUE TITLE
Download example, help needed

### ISSUE THREAD

**Issue by hsch0** [Maroder1/Openness_examples_python#4]
Thanks for sharing this nice tool. However, I have problems with the download to PLC part which I want to automate in my project. I quite not understand the functions. What is the difference between pre- and postconfigured downloads? And what are the arguments (preconfigure_download, postconfigure_download)?

I'm also wondering if this works for PLCs which are accessible with a different IP address than configured in TIA (e.g. behind a NAT router):
https://www.dmcinfo.com/latest-thinking/blog/id/9151/connecting-to-a-siemens-plc-with-access-address

**Comment by Maroder1** [comment]
Hello,

This is basically what you do yourself in TIA when downloading, e.g. you need to put CPU to stop, run a reinitialization etc. 
As you know from TIA, this kind of user action is needed (sometimes) both before downloading (pre) and after (post)

Quote from the manual about the delegates:
_Openness user need to provide two implementations of void
DownloadConfigurationDelegate(DownloadConfiguration downloadConfiguration). First
delegate will be called for pre-download configurations, and the second will be called after
download is completed. The delegates will be called for each configuration that requires an
action from the user_

Starting on page 454 in the manual you can see a table of all options for the delegates.
https://support.industry.siemens.com/cs/ww/en/view/109773802


As for router I honestly don't know as I cannot easily test this, nor do I know how it is done using TIA itself (which probably would give some hints). Either way: Downloading is quite limited in the current version V16 compared to what you can do with GUI. I dont know exactly what, but I know that TIA v17 (should come in May 21) will bring improvements in regards of downloading using openness.

**Comment by hsch0** [comment]
Ah okay thanks for the explanation.

To edit the access IP address you click in the "address" field. Do you think this is possible with the Openness?

<img width="600" alt="1" src="https://user-images.githubusercontent.com/9827195/113751584-61bb5200-970c-11eb-803f-0a6ea37aaddd.png">

**Comment by Maroder1** [comment]
Think I got the question right. 
Today the possibilities are quite limited. The offline/online IP needs to match. This means e.g. that you cannot download to a new PLC “out of the box” or a PLC with a different IP(you need to know the IP of the device you want to download to). From what I have heard this will change in v17 (May release).

**Comment by hsch0** [comment]
Thanks for info. Let's see what v17 will bring :)

**Comment by hsch0** [comment]
Hi, I did not really look into the v17 openness, but it seems to be possible now, right?

Quote from the "New Features":
Extension for devices with IP address not configured in the project when downloading to the
PLC
